import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();
import authRoutes from './routes/authRoutes';
import assessmentRoutes from './routes/assessmentRoutes';
import chatRoutes from './routes/chatRoutes';
import nutritionistRoutes from './routes/nutritionistRoutes';
import dietRoutes from './routes/dietRoutes';
const app = express();
app.use(cors());
app.use(express.json());
app.get('/', (req, res) => res.send('Hridsync API'));
app.use('/api/auth', authRoutes);
app.use('/api/assessments', assessmentRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/nutritionists', nutritionistRoutes);
app.use('/api/diet', dietRoutes);
export default app;
